### ISSUE TITLE
Add loading indicators

### ISSUE THREAD

**Issue by bruth** [PEDSnet/pedsnet-catalogue#2]
I have high latency due to a VPN connection. Attached is a gif that shows the delay from loading the available tables for a model and then loading the information on the right. Adding a simple loading indicator in the center, then the right side would help alleviate the lack of patience :)

![catalogue-loading](https://cloud.githubusercontent.com/assets/515142/10254334/f7fb1c9e-6910-11e5-90f4-37d4db5cbb60.gif)

**Comment by l-k-** [comment]
Thanks for pointing it out. I didn't think about this at all -- know what should appear where, so I didn't pay any attention to what the loading process looks like.
I can't assign the issue to myself for some reason -- but I'll address it.

**Comment by bruth** [comment]
With the redesign this no longer feels necessary.
