### ISSUE TITLE
Do not attempt to fetch ETL conventions or DQA result for PCORnet models

### ISSUE THREAD

**Issue by bruth** [PEDSnet/pedsnet-catalogue#7]

**Comment by l-k-** [comment]
why? does that break something? 
Or it's just that we know for sure there will never be any data there?

**Comment by bruth** [comment]
We know there won't be data and it also sends a lot of unnecessary requests to the services and results in 404s which show up in the console.

**Comment by l-k-** [comment]
addressed in https://github.com/PEDSnet/pedsnet-catalogue/pull/6
